---
swagger: "2.0"
info:
  description: "API description for nodejs authentication module."
  version: "0.0.1"
  title: "Nodejs websocket quiz"
  contact:
    email: "fengjiwei6@gmail.com"
host: "localhost:8081"
basePath: "/v1"
tags:
- name: "loginAuth"
  description: "authentication for user with valid email and password"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /auth:
    post:
      tags:
      - "loginAuth"
      description: "Generate jwt token for user"
      operationId: "loginPost"
      parameters:
      - in: "body"
        name: "authentication"
        required: true
        schema:
          $ref: "#/definitions/Authentication"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Token"
        403:
          description: "Access Denied"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "LoginAuth"
    x-swagger-router-controller: "auth"
definitions:
  Authentication:
    type: "object"
    properties:
      email:
        type: "string"
        example: "test@gmail.com"
      password:
        type: "string"
        example: "password"
    example:
      password: "password"
      email: "test@gmail.com"
  Token:
    type: "object"
    properties:
      token:
        type: "string"
    example:
      token: "token"
  Error:
    type: "object"
    properties:
      message:
        type: "string"
